package dev.xfj.constants;

public enum StatGrowthType {
    NONE,
    FIGHT_PROP_BASE_HP,
    FIGHT_PROP_BASE_ATTACK,
    FIGHT_PROP_BASE_DEFENSE,
    FIGHT_PROP_HP_PERCENT,
    FIGHT_PROP_ATTACK_PERCENT,
    FIGHT_PROP_DEFENSE_PERCENT,
    FIGHT_PROP_CRITICAL,
    FIGHT_PROP_CRITICAL_HURT,
    FIGHT_PROP_ELEMENT_MASTERY,
    FIGHT_PROP_CHARGE_EFFICIENCY,
    FIGHT_PROP_PHYSICAL_ADD_HURT
}
